### PR TITLE
Fix some messages in Italian translation

### PR DESCRIPTION
**Pull request by cipi1965**
### 1. Why is this change necessary?
The Italian translation contains some words that does not make sense.

### 2. What does this change do, exactly?
Rename some words and fix some non sense phrases

### 3. Please link to the relevant issues (if any).
None

### CODE REVIEW

**Comment by PeopleInside** [comment]
@cipi1965 thank you! Grazie! This look to be a great job!

**Comment by papnoisanjeev** [comment]
@cipi1965 

Have you done with the updates for translation (it) or still in progress as i can see you have marked it as draft.

**Comment by cipi1965** [comment]
@papnoisanjeev  hey, it's still a draft because i'm still tweaking it. I will ping you as soon as it's ready

**Comment by cipi1965** [comment]
@papnoisanjeev i think it's ready for review

**Comment by papnoisanjeev** [comment]
@PeopleInside Please review if everything ok with Italian translation as you are the same language user and have better knowledge about language.

**Comment by PeopleInside** [comment]
@papnoisanjeev I checked yesterday the new edit from @cipi1965  and looks like a very amazing work. I think you can trust him.
For me look like everything is good. I think you can push it.

**Comment by cipi1965** [comment]
@PeopleInside thank you very much! I kept some words in english version because is common use in italian (like Ticket in place of Biglietto that usually mean only train ticket and not support ticket)

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside thank you very much! I kept some words in english version because is common use in italian (like Ticket in place of Biglietto that usually mean only train ticket and not support ticket)

I see, is a really good works. Thank you!

**Comment by papnoisanjeev** [comment]
@PeopleInside 
Ok fine and thanks for your time :)

@cipi1965 
I really appreciate your efforts to correct us. thanks !!

**Comment by PeopleInside** [comment]
@papnoisanjeev will be nice if you can fix the fact customer when see the ticket list after login in his account, doesn't see the status ticket translated as described here: https://github.com/uvdesk/community-skeleton/issues/326#issuecomment-769044887

**Comment by papnoisanjeev** [comment]
> @papnoisanjeev will be nice if you can fix the fact customer when see the ticket list after login in his account, doesn't see the status ticket translated as described here: [#326 (comment)](https://github.com/uvdesk/community-skeleton/issues/326#issuecomment-769044887)

Will check it as well.

**Pull request merged**
