### PR TITLE
Update messages.it.yml

### PR DESCRIPTION
**Pull request by PeopleInside**
Some space error create issues on translation.
Some capitals letter create issue in translation.
Fix
https://github.com/uvdesk/community-skeleton/issues/326

### CODE REVIEW

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Please delete your current **community-skeleton** and **folk** latest community (as there are some update for our side it may be replace if we merge this pull request) and create a pull request again for this.

Thanks !!

**Comment by PeopleInside** [comment]
I have to remove folder on my server and replace with the github download one?
I should upload this https://github.com/uvdesk/community-skeleton/archive/master.zip ?

**Comment by PeopleInside** [comment]
The fix has been done from your github repo.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

No you need to **delete** you repository **community-skeleton**  from Git hub  and again **folk** it from here https://prnt.sc/v33ita
Now make changes as you have created for translation and again create a pull request.

or

You can close this pull request we will made these update from our side.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have updated our repository branch with this update you can close this pull request for now.
https://github.com/uvdesk/community-skeleton/commit/ee5b23cccc9d410a12072026a4b2f567146da78b

**Pull request closed without merging**
